sudo: required
services:
    - docker

before_install:
    - docker build -t m_sahil/fibinacci_prod -f ./client/Dockerfile.dev ./client

script:
    - docker run m_sahil/fibinacci_prod npm test -- --coverage

after_success:
    - docker build -t sahil1/fibonacci_prod_client -f ./client
    - docker build -t sahil1/fibonacci_prod_nginx -f ./nginx
    - docker build -t sahil1/fibonacci_prod_api -f ./server
    - docker build -t sahil1/fibonacci_prod_worker -f ./worker

    # Login to docker-cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push sahil1/fibonacci_prod_client
    - docker push sahil1/fibonacci_prod_nginx
    - docker push sahil1/fibonacci_prod_api
    - docker push sahil1/fibonacci_prod_worker
