sudo: required
services:
    - docker

before_install:
    - docker build -t m_sahil/fibinacci_prod -f ./client/Dockerfile.dev ./client

script:
    - docker run m_sahil/fibinacci_prod npm test -- --coverage

after_success:
    - docker build -t m_sahil/multi-client -f ./client
    - docker build -t m_sahil/multi-nginx -f ./nginx
    - docker build -t m_sahil/multi-server -f ./server
    - docker build -t m_sahil/multi-worker -f ./worker

    # Login to docker-cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push m_sahil/multi-client
    - docker push m_sahil/multi-nginx
    - docker push m_sahil/multi-server
    - docker push m_sahil/multi-worker
